smtp:
  Host: ""
  Port: 0
  User: ""
  Password: ""

logger:
  Mode: "prod"

metrics:
  Port: 8242

gateway:
  Port: 8192

jaeger:
  Host: "jaeger-agent.monitoring.svc.cluster.local"

grpc:
  Port: 50001

rabbit:
  Host: "rabbitmq.database.svc.cluster.local"
  Port: 5672
  User: "guest"
  Password: "guest"
  QueueName: "emails"
  ConsumePool: 2

database:
  Host: "postgresql.database.svc.cluster.local"
  Port: 5432
  User: "postgres"
  Password: "postgres"
  DbName: "mails_db"
  SslMode: "disable"
