{{- $grpcGatewayPort := .Values.ports.grpcGatewayPort -}}
{{- $grpcPort := .Values.ports.grpcPort -}}
{{- $metricsAndHealthPort := .Values.ports.metricsAndHealthPort -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "email-service.fullname" . }}
  labels:
    {{- include "email-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $grpcGatewayPort }}
      targetPort: {{ $grpcGatewayPort }}
      protocol: TCP
      name: grpc-gateway
  
    - port: {{ $grpcPort }}
      targetPort: {{ $grpcPort }}
      protocol: TCP
      name: grpc

    - port: {{ $metricsAndHealthPort }}
      targetPort: {{ $metricsAndHealthPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "email-service.selectorLabels" . | nindent 4 }}